// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG0BYmjycBixiDk2aHRTqYZMJQNWMNMTo',
    appId: '1:826630170329:web:75b0d3fff111f7d726c0c8',
    messagingSenderId: '826630170329',
    projectId: 'cavalheros-df4e6',
    authDomain: 'cavalheros-df4e6.firebaseapp.com',
    storageBucket: 'cavalheros-df4e6.appspot.com',
    measurementId: 'G-1D0FYE4MY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLHL0QIECKh9MCxGXKx9xRiaZJT2hl1wQ',
    appId: '1:826630170329:android:6802fdb21396210726c0c8',
    messagingSenderId: '826630170329',
    projectId: 'cavalheros-df4e6',
    storageBucket: 'cavalheros-df4e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbG_XIFvgYEDdSrEjdBc1yQ3195we_qmQ',
    appId: '1:826630170329:ios:3c974177a0c61dde26c0c8',
    messagingSenderId: '826630170329',
    projectId: 'cavalheros-df4e6',
    storageBucket: 'cavalheros-df4e6.appspot.com',
    iosClientId: '826630170329-ohffq6v6e44moc6a7jnkjfs0on8c1v08.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCheveaux',
  );
}
